<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OpeninghoursTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('openinghours')->insert([
            // Business 1
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 1,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 1,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 1,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 1,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 1,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 1,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 1,
            ],
            
            // Business 2
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 2,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 2,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 2,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 2,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 2,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 2,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 2,
            ],
            
            // Business 3
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 3,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 3,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 3,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 3,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 3,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 3,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 3,
            ],
            
            // Business 4
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 4,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 4,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 4,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 4,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 4,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 4,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 4,
            ],
            
            // Business 5
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 5,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 5,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 5,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 5,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 5,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 5,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 5,
            ],
            
            // Business 6
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 6,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 6,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 6,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 6,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 6,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 6,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 6,
            ],
            
            // Business 7
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 7,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 7,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 7,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 7,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 7,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 7,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 7,
            ],
            
            // Business 8
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 8,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 8,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 8,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 8,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 8,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 8,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 8,
            ],
            
            // Business 9
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 9,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 9,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 9,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 9,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 9,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 9,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 9,
            ],
            
            // Business 10
		    [
                'dayofweek' => 'monday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 10,
		    ],
		    [
                'dayofweek' => 'tuesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 10,
		    ],
		    [
                'dayofweek' => 'wednesday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 10,
		    ],
		    [
                'dayofweek' => 'thursday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 10,
		    ],
		    [
                'dayofweek' => 'friday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 10,
		    ],
		    [
                'dayofweek' => 'saturday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 10,
		    ],
		    [
                'dayofweek' => 'sunday',
                'opentime' => 'opentime',
                'closetime' => 'closetime',
                'opentime_in_min' => 3600,
                'closetime_in_min' => 7200,
                'closed' => 0,
                'business_id' => 10,
		    ],
		]);
    }
}
